plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    id 'dagger.hilt.android.plugin'
    id "com.huawei.agconnect"
    id "com.google.gms.google-services"
    id 'androidx.navigation.safeargs'
}

android {
    namespace 'huawei.cmsdemo.main'
    compileSdk 34

    defaultConfig {
        applicationId "huawei.cmsdemo.main"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            resValue "string", "API_KEY_HMS_MAP", "\"***Your Api Key***\""
            manifestPlaceholders = [API_KEY_GMS_MAP: "***Your Api Key***"]
            resValue "string", "HMS_AD_ID_SPLASH", "testq6zq98hecj"
            resValue "string", "GMS_AD_ID_SPLASH", "ca-app-pub-3940256099942544/9257395921"
            resValue "string", "HMS_AD_ID_BANNER", "testw6vs28auh3"
            resValue "string", "GMS_AD_ID_BANNER", "ca-app-pub-3940256099942544/6300978111"
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.8.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    // HMS
    implementation 'com.huawei.agconnect:agconnect-core:1.7.1.300'

    // Firebase
    implementation(platform("com.google.firebase:firebase-bom:32.7.1"))
    implementation("com.google.firebase:firebase-analytics")

    // Navigation
    implementation "androidx.navigation:navigation-fragment-ktx:2.7.7"
    implementation "androidx.navigation:navigation-ui-ktx:2.7.7"

    // Glide
    implementation 'com.github.bumptech.glide:glide:4.16.0'

    // Hilt
    implementation "com.google.dagger:hilt-android:2.45"
    kapt "com.google.dagger:hilt-compiler:2.45"

    // Ads
    implementation 'com.github.Explore-In-HMS.common-mobile-services:ads:3.0.4'

    // Map
    implementation 'com.github.Explore-In-HMS.common-mobile-services:mapkit:3.0.4'

    // Location
    implementation 'com.github.Explore-In-HMS.common-mobile-services:location:3.0.4'

    // Account Kit
    implementation 'com.github.Explore-In-HMS.common-mobile-services:account:3.0.4'

    // Auth Service
    implementation 'com.github.Explore-In-HMS.common-mobile-services:auth:3.0.4'

    // Translate
    implementation 'com.github.Explore-In-HMS.common-mobile-services:translate:3.0.4'
}